### PR TITLE
Merging

### PR DESCRIPTION
**Pull request by BenBrostoff**
Hey @shahen94 - know you're not actively working on this anymore but was wondering if you had a few free moments if you could offer some guidance / tips on this PR, which is in part based on [this discussion](https://github.com/shahen94/react-native-video-processing/issues/83).

This branch works on Android but merging is extremely slow on my Samsung tablet (generally 6+ seconds). I haven't profiled but think it's on account of the `filter_complex` (which comes from the JS side and will look like `[0:0][1:0][2:0] concat=n=3:v=1 [v]` - ideally I'd refactor this to not call FFMPEG commands within React).

I'm not very familiar with FFMPEG, but based on my reading of the [docs](https://trac.ffmpeg.org/wiki/Concatenate) it seems like for videos with different codecs, `filter_complex` with `concat` is recommended.

Any advice on how to improve performance here or other thoughts would be great. If this can be faster, would be happy to add some tests and refactor as necessary if you think it's a good candidate for merging. Thanks again!

### CODE REVIEW

**Comment by shahen94** [comment]
Hi  @BenBrostoff !
Thank you for so great PR. I'm not sure how to improve performance of the merging. FFMEG works really slow and unfortunately I don't know any other way to impovet it.
Can you please also update docs ?

Thanks.

**Comment by BenBrostoff** [comment]
@shahen94 Will do. I may not get to this until the weekend since I have a lot of work stuff going on, but I will add 👍 .

**Comment by BenBrostoff** [comment]
This is more a general comment not specific to this PR, but I've found some options are necessary to ensure video plays on all Android devices. [I'm taking these settings from the Android docs](https://developer.android.com/guide/topics/media/media-formats#video-encoding) - see `Video encoding recommendations`. For most of the `Trimmer.java` methods, this would look like:

```
// These options are recommended by https://developer.android.com/guide/topics/media/media-formats
cmd.add("-profile:v");
cmd.add("baseline");

cmd.add("-level");
cmd.add("3.0");

cmd.add("-vf");
cmd.add("scale:1280:720");
```

The scaling right now distorts videos so that needs fixing, but just wondering if you had any thoughts on this @shahen94 . Without these options, I'm finding my older Android device just plays audio with black for video (to be clear, I'm using Expo's `VideoPlayer` component and not the one from this library).

**Comment by bulats** [comment]
If you want to add fast merging you should check out this library - https://github.com/MostWantIT/react-native-video-editor/. It handles merging really well.

**Comment by BenBrostoff** [comment]
@bulats Sorry for late response, just began working on this for iOS. The issue with the library you mentioned at least for my use case is that can't handle merging different video resolutions / codecs - ffmpeg can do the pre-processing and merge steps. I think there's another issue on this repo where someone mentioned you could use this library to get the same resolutions and then do the merging with the other one, but I wasn't seeing much of a performance difference with that as opposed to just doing it all in ffmpeg. In what you're working on are all the videos the same resolution, or did you find some workaround?

**Comment by BenBrostoff** [comment]
Also @shahen94 , just want to make sure I understand the source code correctly - does iOS just use its own native capabilities (or really AV Foundation) and not FFMPEG? I saw [this link](https://www.raywenderlich.com/5135-how-to-play-record-and-merge-videos-in-ios-and-swift) in the source.

**Comment by shahen94** [comment]
Yes - You're right!

Can you please resolve these conflicts?
I'm going to merge this PR and publish the final version to NPM.

**Comment by BenBrostoff** [comment]
Sure, will take a look now; assuming I get these conflicts resolved I'd just note in the README that merging is only implemented for Android and not iOS right now.

**Pull request merged**
