### PR TITLE
Suggestions (Implemented)

### PR DESCRIPTION
**Pull request by goldylucks**
#23 WIP - points 1-4 implemented
- package: move dependencies to dev and peer
- react components: remove constructor calls, use default syntax
- lint: sort rules by logic, enforce react components sorting

regarding points 5-6, we could think together how to best approach this. do u know how to test performance?

I currently don't have access to iOS devices, so actually not using the project. I'm helping this since I need it on Android, so I want to expedite the process :)

### CODE REVIEW

**Comment by shahen94** [comment]
@goldylucks Thank you for PR.
I just tested it out ,and seems like there is no difference . `resolveAsset` is a simple function and i guess that will not drop performance

**Comment by goldylucks** [comment]
gotcha. so atm I say let's just merge this. points 5-6 r not critical anywayz.

btw, the two types of tests failed for me with a fresh clone and `npm i`

Also, how did u test the performance difference?

**Comment by shahen94** [comment]
@goldylucks you can use `Systrace`.  if you can help us to release android version that would be great. @gevorg94 will check this on device tomorrow. Btw tests should not fail. please look why it happens

**Comment by goldylucks** [comment]
`Cannot find module 'ReactNativeDefaultInjection' from 'setup.js'`

happens after cloning master

**Comment by goldylucks** [comment]
@shahen94 I can take a swing at it if provided some pointers. haven't done any work on RN core or authored any plugins that interface with native components

**Comment by goldylucks** [comment]
Any reason this is not merged?

**Comment by shahen94** [comment]
@goldylucks Please fix the tests, they shouldn’t fail, after that we’ll check the PR

**Comment by gevorg94** [comment]
@goldylucks please put babels back to dependencies, we are having a lot of errors because of this.
I think you need to put react back to dependencies too for passing tests successfully.

**Comment by goldylucks** [comment]
Sorry for not getting back at you sooner.

Dependencies are a big no no for npm packages, using [peer](http://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins) is better, especially for [react](https://github.com/callemall/material-ui/issues/2818)

If your tests require react, put it in devDep, not dep.

Does this makes sense?

**Pull request closed without merging**
