### PR TITLE
Integrate ffmpeg builds

### PR DESCRIPTION
**Pull request by kesha-antonov**
Fixes https://github.com/shahen94/react-native-video-processing/issues/78

@shahen94. I emailed you with details

### CODE REVIEW

**Comment by shahen94** [comment]
Hey @kesha-antonov !
Can you please resolve the conflicts ?

**Comment by shahen94** [comment]
Oh - hang on...
Something is wrong with your git history.

**Comment by kesha-antonov** [comment]
@shahen94 Yeah, I emailed you about that

**Comment by kesha-antonov** [comment]
Fixed conflicts

**Pull request merged**
