### PR TITLE
Trim with ffmpeg

### PR DESCRIPTION
**Pull request by kesha-antonov**

### CODE REVIEW

**Comment by shahen94** [comment]
@kesha-antonov probably no need to change jest version

**Comment by kesha-antonov** [comment]
@shahen94 It failed tests for me. Something about ```.bind``` not working

**Comment by kesha-antonov** [comment]
I'll fix these tests later

**Comment by gvillenave** [comment]
Great job @kesha-antonov! @shahen94 any idea when we can get this merged?

**Comment by kesha-antonov** [comment]
screen shot 2017-10-31 at 12 58 32

Test are passed locally. But CI failing. Trying to fix

**Comment by kesha-antonov** [comment]
@shahen94 @gvillenave  Hello! Can you fix CI?

**Comment by shahen94** [comment]
Thanks @kesha-antonov !
Trying now

**Comment by shahen94** [comment]
Merging this to fix some memory issues. Still couldn't understand why CircleCI tests are failing.

Thanks @kesha-antonov !

**Pull request merged**
