### PR TITLE
Pass integer value to FFMPEG for trimming (#89)

### PR DESCRIPTION
**Pull request by gvillenave**

### CODE REVIEW

**Comment by shahen94** [comment]
Hi @gvillenave ! Thank you for this PR.

Ca you please explain why your changes need to be merged ?

**Comment by gvillenave** [comment]
It’s a fix for the bug described in #89

________________________________

**Comment by shahen94** [comment]
Aahhh, got it - Thanks @gvillenave !

**Comment by shahen94** [comment]
@gvillenave merged and published to npm

**Comment by gvillenave** [comment]
Thanks for the quick merge!

**Pull request merged**
