### PR TITLE
Adding the possibility to trim a remote file

### PR DESCRIPTION
**Pull request by santiagovazquez**
I made some changes on trim function to be able to trim remote files.   

Code based on:
https://stackoverflow.com/questions/31383655/avassetexportsession-trim-download

### CODE REVIEW

**Comment by santiagovazquez** [comment]
@shahen94 any problem with this PR ?

**Comment by shahen94** [comment]
We'll need also Android version of the feature.

BTW: Thanks for the PR!

**Comment by santiagovazquez** [comment]
Thanks for the responde @shahen94 !
When I first use this library I thought this feature would work because you could pass a URL as source. Since it didn't work on iOS, I made it work. I don't really know if this is working or not on Android (I think it should!). I will test and let you know

**Comment by shahen94** [comment]
@santiagovazquez I guess, it shouldn't work, but anyway I'll merge this. Can you please just update readme and make a note about this?

Thanks!

**Comment by santiagovazquez** [comment]
@shahen94 done!

**Comment by xlogix** [comment]
The build is failing 😕Is this gonna be merged anytime soon?

**Pull request merged**
