### PR TITLE
fix(Trim): Fixed floating value handling in trimmer

### PR DESCRIPTION
**Pull request by nazwa**
Turns out the way Float and Any values are handled in Swift has changed, making it impossible to trim videos with sub-second precission on iOS. This adds a simple (maybe naive) way to fix it.

I wasn't aware of https://github.com/shahen94/react-native-video-processing/pull/174 until I wrote this fix, but I'd like to think that my solotion is neater 😄 (less code changes / doesn't affect the logic). I'm not too familiart with Swift, so can't guarantee this will work under all conditions!

### CODE REVIEW

**Comment by shahen94** [comment]
Thank you @nazwa !
I'll test this PR and will get back with results.

**Comment by shahen94** [comment]
Wops, @nazwa I can't merge this since the PR includes feature which is not documented yet.

Can you please add the changes in the README  ?

**Comment by nazwa** [comment]
Ah @shahen94 my bad - I accidentally pushed our new code into the same branch! I'll clean it up today and ping you when done.

**Comment by shahen94** [comment]
Thank you @nazwa !

**Comment by nazwa** [comment]
@shahen94 Corrected :)

**Pull request merged**
